# Simulation and Bootstrap

***

## STAT 432 Materials

- [**Slides** | Bootstrap](https://fall-2019.stat432.org/slides/bootstrap.pdf)
- ISL Readings: Sections 8.1 - 8.2 

***

```{r resampling_opts, include = FALSE}
knitr::opts_chunk$set(cache = TRUE, autodep = TRUE, fig.align = "center")
```

**Note:** In the future this should become two chapters, and be greatly expanded. Perhaps introduce simulation, ECDF, and plug-in-principle very early.

```{r}
library(microbenchmark)
```

```{r}
# create some data
set.seed(1)
data = rexp(n = 100, rate = 0.5)
```

```{r}
# quantities of interest
1 / 0.5 # mean
qexp(0.5, rate = 0.5)
pexp(8, rate = 0.5, lower.tail = FALSE) # probability P[X > 8]
```

```{r}
# estimates using sampled data
mean(data) # boring
median(data)
mean(data > 8)
```

```{r}
# histogram of data with population distribution
hist(data, 
     border = "dodgerblue", col = "grey", breaks = 20, 
     probability = TRUE, ylim = c(0, 0.5), xlim = c(0, 20))
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange", n = 250, lwd = 2)
```

```{r}
# define graphical parameters
ylim = c(0, 0.5)
xlim = c(0, 20)
```

```{r, fig.height = 4, fig.width = 12}
# resampling from the true distribution
par(mfrow = c(1, 3))

hist(rexp(n = 100, rate = 0.5), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Sample From Population", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")

hist(rexp(n = 100, rate = 0.5), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Sample From Population", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")

hist(rexp(n = 100, rate = 0.5), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Sample From Population", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")
```

```{r}
qexp(0.5, rate = 0.5) # true populaiton median
median(data) # sample median
```

```{r}
# simulating medians
# - simulate from known distribution
# - calculate median on simualted data
# - store result
simulated_medians = replicate(n = 10000, median(rexp(n = 100, rate = 0.5)))
```

```{r}
# use EDCD and plug-in principle to learn about distribution and make estimates
mean(simulated_medians)
sd(simulated_medians)
quantile(simulated_medians, probs = c(0.025, 0.975))
```

```{r}
# plot of ECDF of sample median
hist(simulated_medians, col = "darkgrey")
box()
grid()
```

```{r}
pexp(8, rate = 0.5, lower.tail = FALSE) # true probability P[X > 8]
mean(data > 8) # estimate using ECDF of sample data, mean(I(x > 8))
```

```{r}
# simulating estimates of P[X > 8]
# - simulate from known distribution
# - calculate proportion of obs greater than 8 in simualted data, mean(I(x > 8))
# - store result
simulated_probs = replicate(n = 10000, mean(rexp(n = 100, rate = 0.5) > 8))
```

```{r}
# use EDCD and plug-in principle to learn about distribution and make estimates
mean(simulated_probs)
sd(simulated_probs)
quantile(simulated_probs, probs = c(0.025, 0.975))
```

```{r}
# plot of ECDF of sample median
hist(simulated_probs, col = "darkgrey")
box()
grid()
```

```{r}
# bootstrap resampling
sample(x = data, replace = TRUE)
```

```{r, fig.height = 4, fig.width = 12}
# bootstrap resample from original data
par(mfrow = c(1, 3))

hist(sample(x = data, replace = TRUE), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Bootstrap Resample", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")

hist(sample(x = data, replace = TRUE), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Bootstrap Resample", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")

hist(sample(x = data, replace = TRUE), 
     border = "dodgerblue", col = "grey", breaks = 20, probability = TRUE, 
     ylim = ylim, xlim = xlim,
     main = "Bootstrap Resample", xlab = "x")
box()
grid()
curve(dexp(x, rate = 0.5), add = TRUE, col = "darkorange")
```

```{r}
qexp(0.5, rate = 0.5) # true populaiton median
median(data) # sample median
```

```{r}
# boostrapping medians
# - sample with replacement from sample data
# - calculate median on resampled data
# - store result
replicated_medians = replicate(n = 10000, median(sample(data, replace = TRUE)))
```

```{r}
# use EDCD and plug-in principle to learn about distribution and make estimates
mean(replicated_medians)
sd(replicated_medians)
```

```{r}
# a 95% CI for the true median
quantile(replicated_medians, probs = c(0.025, 0.975))
```

```{r}
# plot of ECDF of sample median
hist(replicated_medians, col = "darkgrey")
box()
grid()
```

```{r}
pexp(8, rate = 0.5, lower.tail = FALSE) # true probability P[X > 8]
mean(data > 8) # estimate using ECDF of sample data, mean(I(x > 8))
```

```{r}
# boostrapping mean(I(x > 8))
# - sample with replacement from sample data
# - calculate proportion of obs greater than 8 in simualted data, mean(I(x > 8))
# - store result
replicated_probs = replicate(n = 10000, mean(sample(data, replace = TRUE) > 8))
```

```{r}
# use EDCD and plug-in principle to learn about distribution and make estimates
mean(replicated_probs)
sd(replicated_probs)
```

```{r}
# a 95% CI for the true P[X > 8]
quantile(replicated_probs, probs = c(0.025, 0.975))
```

```{r}
# plot of ECDF of sample median
hist(replicated_probs, col = "darkgrey")
box()
grid()
```

```{r}
# sample from exponential with mean 2
# generate bootstrap replicates of the median
# calculate 95% confidence interval use percentile (quantile) method
# check if true median is in confidence interval each time (hope for ~95%!)
true_median = qexp(0.5, rate = 0.5) # median
```

```{r}
check_if_in_interval = function() {
  data = rexp(n = 100, rate = 0.5)
  replicated_medians = replicate(n = 2000, median(sample(data, replace = TRUE)))
  interval = quantile(replicated_medians, probs = c(0.025, 0.975))
  interval[1] < true_median & true_median < interval[2]
}
```

```{r}
median_in_out = replicate(n = 200, check_if_in_interval())
mean(median_in_out)
```

```{r}
microbenchmark(check_if_in_interval())
```

## Misc Notes

- TODO: https://statistics.stanford.edu/sites/g/files/sbiybj6031/f/BIO%2083.pdf
