# Class Imbalance

```{r}
library("tidyverse")
library("caret")
library("DMwR")
library("ROSE")
library("randomForest")
```

```{r}
set.seed(42)
trn = as_tibble(twoClassSim(1000,  intercept = -22))
tst = as_tibble(twoClassSim(10000, intercept = -22))
```

```{r}
trn
```

```{r}
table(trn$Class)
```

```{r}
trn_down = downSample(
  x = trn[, -ncol(trn)],
  y = trn$Class
)

trn_up = upSample(
  x = trn[, -ncol(trn)],
  y = trn$Class
)

trn_rose = ROSE(Class ~ ., data = trn)$data
```

```{r}
table(trn_down$Class)
table(trn_up$Class)
table(trn_rose$Class)
```


```{r}
cv = trainControl(method = "cv", number = 5)
cv_down = trainControl(method = "cv", number = 5, sampling = "down")
cv_up = trainControl(method = "cv", number = 5, sampling = "up")
cv_rose = trainControl(method = "cv", number = 5, sampling = "rose")
```

```{r}
mod = train(
  Class ~ .,
  data = trn,
  method = "rf",
  trControl = cv
)

mod_down = train(
  Class ~ .,
  data = trn,
  method = "rf",
  trControl = cv_down
)

mod_up = train(
  Class ~ .,
  data = trn,
  method = "rf",
  trControl = cv_up
)

mod_rose = train(
  Class ~ .,
  data = trn,
  method = "rf",
  trControl = cv_rose
)
```

```{r}
mod_rose
```

```{r}
confusionMatrix(mod_rose)
```

```{r}
confusionMatrix(
  data = predict(mod_rose, tst),
  reference = tst$Class
)
```

```{r}
rf_mod = randomForest(
  Class ~ ., data = trn,
  strata = trn$Class,
  sampsize = c(1, 1),
  mtry = 1,
  ntree = 2500
)
rf_mod
```

```{r}
predict(rf_mod) == "Class2"
```


```{r}
rf_mod
```

