# Additional Reading

## Books

- [An Introduction to Statistical Learning](https://faculty.marshall.usc.edu/gareth-james/ISL/)
  - Gareth James, Daniela Witten, Trevor Hastie, and Robert Tibshirani
- [The Elements of Statistical Learning](https://web.stanford.edu/~hastie/ElemStatLearn/)
  - Trevor Hastie, Robert Tibshirani, and Jerome Friedman
- [Mathematics for Machine Learning](https://mml-book.github.io/)
  - Marc Peter Deisenroth, A. Aldo Faisal, and Cheng Soon Ong
- [Understanding Machine Learning: From Theory to Algorithms](https://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/)
  - Shai Shalev-Shwartz and Shai Ben-David
- [Foundations of Machine Learning](https://cs.nyu.edu/~mohri/mlbook/)
  - Mehryar Mohri, Afshin Rostamizadeh, and Ameet Talwalkar
- [The `caret` Package](https://topepo.github.io/caret/index.html)
  - Max Kuhn
  
## Papers

- [Do we Need Hundreds of Classifiers to Solve Real WorldClassification Problems?](http://jmlr.csail.mit.edu/papers/volume15/delgado14a/delgado14a.pdf)
  - Manuel Fernandez-Delgado, Eva Cernadas, Senen Barro, Dinani Amorim

## Blog Posts

- [Peekaboo: Don't cite the No Free Lunch Theorem](https://peekaboo-vision.blogspot.com/2019/07/dont-cite-no-free-lunch-theorem.html)
